name: CI

on: [ push, pull_request ]

jobs:
    black-box-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                redis-version: [ "2.8", "3.0", "4.0", "5.0", "6.0", "7.0" ]
        steps:
            -   name: Git checkout
                uses: actions/checkout@v2

            -   name: Setup Golang with cache
                uses: magnetikonline/action-golang-cache@v3
                with:
                    go-version-file: go.mod

            -   name: clone and make redis
                run: |
                    sudo apt-get install git
                    git clone https://github.com/redis/redis
                    cd redis
                    git checkout ${{ matrix.redis-version }}
                    make -j
                    mkdir bin
                    cp src/redis-server bin/redis-server
                    echo "$GITHUB_WORKSPACE/redis/bin" >> $GITHUB_PATH

            -   name: Setup Python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.11'

            -   name: make redis-shake
                run: |
                    sh build.sh 

            -   name: test
                run: |
                    pip3 install -r tests/requirements.txt
                    sh test.sh